using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EduWatch.Views
{
    public interface IParentView : IView
    {
        Presenters.ParentPresenter Presenter { set; }
        string ParentNameLabelText { get; set; }
        int ComboBoxStudentSelectedIndex { get; set; }
        int ComboboxSubjectSelectedIndex { get; set; }
        int SelectedStudentID { get; }
        int SelectedSubjectID { get; }
        bool ComboBoxSubjectEnabled { get; set; }
        object GridViewData { get; set; }
        bool SaveButtonEnabled { get; set; }
        bool CancelButtonEnabled { get; set; }
        bool AutoGenerateDataColumns { get; set; }
        bool SelectedGradesView { get; set; }
        bool AverageGradeButtonEnabled { get; set; }
        string AverageGradeText { get; set; }
        bool GradesRadioButtonEnabledState { get; set; }
        bool NotesRadioButtonEnabledState { get; set; }

        void FillInCorrespondingStudents(List<Tuple<int, string>> students);
        void FIllInCorrespondingSubjects(List<Tuple<int, string>> subjects);
        //void FillInCorrespondingGrades(object grades);
        void ClearData();
        void DisableUnseeingData();
        void FormatDataDisplay();
    }
}
