using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using EduWatch.Presenters;

namespace EduWatch.Views
{
    public partial class TeacherForm : Form, ITeacherView
    {
        public TeacherForm()
        {
            InitializeComponent();
            dataGridView1.Hide();
            CommentLabel.Hide();
            commentTextBox.Hide();
            GradeLabel.Hide();
            gradeComboBox.Hide();
            Savebtn.Hide();
        }
        public TeacherPresenter Presenter { private get; set; }
        public string TeacherNameLabelText { get => teachersNameLabel.Text; set => teachersNameLabel.Text = value; }
        public int ComboBoxSubjectSelectedIndex { get => comboBoxSubject.SelectedIndex; set => comboBoxSubject.SelectedIndex = value; }
        public int SelectedSubjectID => (int)comboBoxSubject.SelectedValue;
        public int ComboBoxStudentSelectedIndex { get => comboBoxStudent.SelectedIndex; set => comboBoxStudent.SelectedIndex = value; }
        public int SelectedStudentID => (int)comboBoxStudent.SelectedValue;
        public object GridViewData { get => dataGridView1.DataSource; set => dataGridView1.DataSource = value; }
        public bool SaveButtonEnabled { get => Savebtn.Enabled; set => Savebtn.Enabled = value; }
        public bool AutoGenerateDataColumns { get => dataGridView1.AutoGenerateColumns; set => dataGridView1.AutoGenerateColumns = value; }
        public bool SelectedGrades { get => radioButtonGrade.Checked; set => radioButtonGrade.Checked = value; }
        public bool SelectedNotes { get => radioButtonNote.Checked; set => radioButtonNote.Checked = value; }
        public bool AverageGradeButtonEnabled { get => btnAverage.Enabled; set => btnAverage.Enabled = value; }
        public string AverageGradeLabel { get => labelAverageGrade.Text; set => labelAverageGrade.Text = value; }
        public bool SelectedGradesView { get => radioButtonGrade.Checked; set => radioButtonGrade.Checked = value; }

        public bool ComboBoxStudentEnabled { get => comboBoxStudent.Enabled; set => comboBoxStudent.Enabled = value; }

        public string ComboBoxGrade { get => gradeComboBox.Text; set => gradeComboBox.Text = value; }

        public void FIllInCorrespondingSubjects(List<Tuple<int, string>> subjects)
        {
            comboBoxSubject.DisplayMember = "Item2";
            comboBoxSubject.ValueMember = "Item1";
            comboBoxSubject.DataSource = subjects;
        }

        public void FillInCorrespondingStudents(List<Tuple<int, string>> students)
        {
            comboBoxStudent.DisplayMember = "Item2";
            comboBoxStudent.ValueMember = "Item1";
            comboBoxStudent.DataSource = students;
        }

        public void Message(string msg, string caption = "Съобщение", MessageIcon msgIcon = MessageIcon.None, MessageButton msgBtn = MessageButton.OK)
        {
            MessageBox.Show(
                msg,
                caption,
                (MessageBoxButtons)Enum.Parse(typeof(MessageBoxButtons), msgBtn.ToString()),
                (MessageBoxIcon)Enum.Parse(typeof(MessageBoxIcon), msgIcon.ToString())
                );
        }

        private void comboBoxSubject_SelectionChangeCommitted(object sender, EventArgs e)
        {
            Presenter.OnSubjectSelection();
        }

        private void comboBoxStudent_SelectionChangeCommitted(object sender, EventArgs e)
        {
            Presenter.OnStudentSelection();
        }

        public void ClearData()
        {
            dataGridView1.Columns.Clear();
        }

      

        public void FillInGrades(string[] grades)
        {
            gradeComboBox.Items.AddRange(grades);
        }

        private void SeeDatabtn_Click(object sender, EventArgs e)
        {
            CommentLabel.Hide();
            commentTextBox.Hide();
            GradeLabel.Hide();
            gradeComboBox.Hide();
            dataGridView1.Show();
            Savebtn.Hide();
        }

        private void AddRecordbtn_Click(object sender, EventArgs e)
        {
            if (radioButtonGrade.Checked)
            {
                dataGridView1.Hide();
                CommentLabel.Text = "Коментар:";
                CommentLabel.Show();
                commentTextBox.Show();
                GradeLabel.Show();
                gradeComboBox.Show();
                Savebtn.Show();
            }
            else if (radioButtonNote.Checked)
            {
                dataGridView1.Hide();
                GradeLabel.Hide();
                gradeComboBox.Hide();
                CommentLabel.Text = "Забележка:";
                CommentLabel.Show();
                commentTextBox.Show();
                Savebtn.Show();
            }
            else
            {
                Message("Моля, изберете какво искате да добавите.", "Внимание", Views.MessageIcon.Warning);
            }
        }

        private void Exitbtn_Click(object sender, EventArgs e)
        {
            Presenter.OnExitButtonClick();
        }

        public void FillInWhichGrade(string[] grade)
        {
            comboBoxGrade1to12.Items.AddRange(grade);
        }
    }
}
