//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduWatch.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int note_Id { get; set; }
        public string note1 { get; set; }
        public Nullable<System.DateTime> note_date { get; set; }
        public Nullable<bool> note_seen { get; set; }
        public int student_id { get; set; }
        public int subject_id { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual Student Student { get; set; }
    }
}
